trigger:
  - develop

variables:
  - name: subscription
    value: METADATA-dev

jobs:
  - job: publish
    timeoutInMinutes: "60"
    # itss linux build server
    pool: dv-alex-adobuildserves-ubuntu-vmss
    steps:
      - checkout: self
        displayName: Set up repository
        submodules: recursive # needed for submodules
      - task: Bash@3
        displayName: Check if we need to skip the pipeline
        inputs:
          targetType: 'inline'
          script: |
            STR=$(Build.SourceVersionMessage)
            SUB='skipci'
            echo "STR: $STR"
            echo "SUB: $SUB"
            if [[ "$STR" == *"$SUB"* ]]; then
              echo "Skipping pipeline, 'skipci' was found in the commit message."
              exit 1
            fi
            exit 0
      - task: Bash@3
        displayName: Should not run when skipped
        inputs:
          targetType: 'inline'
          script: |
            echo "Hello from the end of the world."
