trigger:
  - develop

variables:
  - name: subscription
    value: METADATA-dev
  - name: manualskip
    value: false

jobs:
  - job: A
    pool: dv-alex-adobuildserves-ubuntu-vmss
    steps:
      - bash: |
          echo "##vso[task.setvariable variable=myOutputVar;isoutput=true]this is from job A"
        name: passOutput
  - job: B
    pool: dv-alex-adobuildserves-ubuntu-vmss
    dependsOn: A
    variables:
      myVarFromJobA: $[ dependencies.A.outputs['passOutput.myOutputVar'] ]
    steps:
      - bash: |
          echo $(myVarFromJobA)
#  - job: skipcheck
#    timeoutInMinutes: "30"
#    pool: dv-alex-adobuildserves-ubuntu-vmss
#    steps:
#      - task: Bash@3
#        displayName: Check if we need to skip the pipeline
#        name: skipcheck
#        env:
#          COMMIT_MESSAGE: $(Build.SourceVersionMessage)
#        inputs:
#          targetType: 'inline'
#          script: |
#            echo "Testing whether we need to skip the pipeline."
#            SUB='skipci'
#            echo "> SUB: $SUB"
#            echo "> COMMIT_MESSAGE: $COMMIT_MESSAGE"
#            skip=false
#            if [[ "$COMMIT_MESSAGE" == *"$SUB"* ]]; then
#              echo "> '$SUB' was found in the commit message."
#              skip=true
#            fi
#            echo "result skip: $skip"
#            echo '##vso[task.setvariable variable=skip;isOutput=true]$skip'
#  - job: publish
#    timeoutInMinutes: "60"
#    pool: dv-alex-adobuildserves-ubuntu-vmss
#    dependsOn: skipcheck
##    condition: and(succeeded(), ne(dependencies.skipcheck.outputs['skipcheck.skip'], 'true'))
#    condition: and(succeeded(), eq(variables.manualskip, false))
#    variables:
#      myVarFromJobA: $[ dependencies.skipcheck.outputs['skipcheck.skip'] ]
#    steps:
#      - task: Bash@3
#        displayName: Should not run when skipped
#        inputs:
#          targetType: 'inline'
#          script: |
#            echo "var from skipcheck: $(myVarFromJobA)"
#            echo "Hello from the end of the world..."
